"""
MuleShield AI - Database Schemas (ORM Models)
Defines all database tables for AML detection system

Key Entities:
- Account: Bank account information
- Transaction: Financial transaction records
- Alert: Risk alerts generated by the system
- Case: Investigation cases for analysts
- DeviceFingerprint: Device intelligence data
- RiskScore: Composite risk scoring results
- BehavioralProfile: Account behavior baselines
- SARReport: Suspicious Activity Reports
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from .database import Base


class Account(Base):
    """
    Bank account entity for AML monitoring.
    
    AML Relevance:
    - Account age vs transaction volume is a key mule indicator
    - New accounts with high transaction velocity are suspicious
    - KYC status affects risk scoring
    """
    __tablename__ = "accounts"
    
    id = Column(String(36), primary_key=True, index=True)  # UUID format
    account_number = Column(String(20), unique=True, index=True)
    account_holder_name = Column(String(100))
    email = Column(String(100))
    phone = Column(String(20))
    
    # Account metadata - important for risk assessment
    account_type = Column(String(20))  # savings, checking, business
    created_at = Column(DateTime, default=datetime.utcnow)
    kyc_status = Column(String(20), default="pending")  # pending, verified, failed
    kyc_verified_at = Column(DateTime, nullable=True)
    
    # Risk indicators
    is_flagged = Column(Boolean, default=False)
    flag_reason = Column(Text, nullable=True)
    risk_category = Column(String(20), default="low")  # low, medium, high
    mule_probability = Column(Float, default=0.0)  # 0-100%
    
    # Account status
    status = Column(String(20), default="active")  # active, suspended, closed
    
    # Geographic data - geo-anomalies indicate mule activity
    country = Column(String(50), default="US")
    city = Column(String(50))
    
    # Relationships
    outgoing_transactions = relationship("Transaction", foreign_keys="Transaction.sender_id", back_populates="sender")
    incoming_transactions = relationship("Transaction", foreign_keys="Transaction.receiver_id", back_populates="receiver")
    risk_scores = relationship("RiskScore", back_populates="account")
    behavioral_profiles = relationship("BehavioralProfile", back_populates="account")
    device_fingerprints = relationship("DeviceFingerprint", back_populates="account")
    alerts = relationship("Alert", back_populates="account")


class Transaction(Base):
    """
    Financial transaction records for pattern analysis.
    
    AML Relevance:
    - Transaction velocity (many transactions in short time)
    - Circular fund flows (A→B→C→A pattern)
    - Structuring (breaking large amounts into smaller ones)
    - Rapid fund dispersal (in-and-out quickly)
    """
    __tablename__ = "transactions"
    
    id = Column(String(36), primary_key=True, index=True)
    transaction_reference = Column(String(30), unique=True, index=True)
    
    # Transaction parties
    sender_id = Column(String(36), ForeignKey("accounts.id"), index=True)
    receiver_id = Column(String(36), ForeignKey("accounts.id"), index=True)
    
    # Transaction details
    amount = Column(Float, nullable=False)
    currency = Column(String(3), default="USD")
    transaction_type = Column(String(20))  # transfer, payment, withdrawal, deposit
    
    # Timing - crucial for velocity analysis
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Device & location - for device intelligence
    device_id = Column(String(100), nullable=True)
    ip_address = Column(String(50), nullable=True)
    geo_location = Column(String(100), nullable=True)
    
    # Transaction status
    status = Column(String(20), default="completed")  # pending, completed, failed, blocked
    
    # Risk assessment at transaction level
    risk_score = Column(Float, default=0.0)
    is_suspicious = Column(Boolean, default=False)
    suspicious_reason = Column(Text, nullable=True)
    
    # Narrative for investigation
    description = Column(String(200), nullable=True)
    
    # Relationships
    sender = relationship("Account", foreign_keys=[sender_id], back_populates="outgoing_transactions")
    receiver = relationship("Account", foreign_keys=[receiver_id], back_populates="incoming_transactions")


class Alert(Base):
    """
    Risk alerts generated by the detection engine.
    
    AML Relevance:
    - Alerts are prioritized by risk score for efficient investigation
    - Explainable AI reasons help analysts make decisions
    - Alert feedback loop enables adaptive learning
    """
    __tablename__ = "alerts"
    
    id = Column(String(36), primary_key=True, index=True)
    account_id = Column(String(36), ForeignKey("accounts.id"), index=True)
    
    # Alert classification
    alert_type = Column(String(50))  # mule_network, velocity, circular_flow, device_reuse
    severity = Column(String(20))  # low, medium, high, critical
    
    # Risk metrics
    risk_score = Column(Float, nullable=False)
    confidence_score = Column(Float, default=0.0)  # How confident is the model
    mule_probability = Column(Float, default=0.0)
    
    # Explainable AI - reasons for the alert
    reasons = Column(JSON)  # List of explanations
    
    # Alert status for investigation workflow
    status = Column(String(20), default="open")  # open, investigating, closed
    resolution = Column(String(20), nullable=True)  # true_mule, false_positive, escalated
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)
    
    # Investigation notes
    analyst_notes = Column(Text, nullable=True)
    assigned_to = Column(String(100), nullable=True)
    
    # Relationships
    account = relationship("Account", back_populates="alerts")
    cases = relationship("Case", back_populates="alert")


class Case(Base):
    """
    Investigation cases for AML analysts.
    
    AML Relevance:
    - Cases track full investigation lifecycle
    - Support regulatory audit requirements
    - Enable trend analysis of mule patterns
    """
    __tablename__ = "cases"
    
    id = Column(String(36), primary_key=True, index=True)
    case_number = Column(String(20), unique=True, index=True)
    alert_id = Column(String(36), ForeignKey("alerts.id"), index=True)
    
    # Case details
    title = Column(String(200))
    description = Column(Text)
    priority = Column(String(20), default="medium")  # low, medium, high, critical
    
    # Case status
    status = Column(String(20), default="open")  # open, investigating, pending_review, closed
    outcome = Column(String(30), nullable=True)  # confirmed_mule, false_positive, inconclusive
    
    # Assignment
    assigned_analyst = Column(String(100), nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    closed_at = Column(DateTime, nullable=True)
    
    # Investigation data
    evidence = Column(JSON, nullable=True)  # Supporting evidence collected
    investigation_notes = Column(Text, nullable=True)
    
    # SAR filing
    sar_filed = Column(Boolean, default=False)
    sar_reference = Column(String(50), nullable=True)
    
    # Relationships
    alert = relationship("Alert", back_populates="cases")


class DeviceFingerprint(Base):
    """
    Device intelligence for detecting shared device clusters.
    
    AML Relevance:
    - Multiple accounts using same device = high mule risk
    - Device reuse patterns indicate organized mule networks
    - IP clustering reveals coordinated activity
    """
    __tablename__ = "device_fingerprints"
    
    id = Column(String(36), primary_key=True, index=True)
    account_id = Column(String(36), ForeignKey("accounts.id"), index=True)
    
    # Device identifiers
    device_id = Column(String(100), index=True)  # Browser fingerprint or device UUID
    device_type = Column(String(50))  # mobile, desktop, tablet
    os = Column(String(50))  # iOS, Android, Windows, macOS
    browser = Column(String(50), nullable=True)
    
    # Network data
    ip_address = Column(String(50), index=True)
    ip_country = Column(String(50))
    ip_city = Column(String(50))
    is_vpn = Column(Boolean, default=False)
    is_proxy = Column(Boolean, default=False)
    
    # Usage tracking
    first_seen = Column(DateTime, default=datetime.utcnow)
    last_seen = Column(DateTime, default=datetime.utcnow)
    usage_count = Column(Integer, default=1)
    
    # Risk assessment
    risk_score = Column(Float, default=0.0)
    is_shared = Column(Boolean, default=False)  # True if used by multiple accounts
    shared_with_accounts = Column(JSON, nullable=True)  # List of other account IDs
    
    # Relationships
    account = relationship("Account", back_populates="device_fingerprints")


class RiskScore(Base):
    """
    Composite risk scoring results for accounts.
    
    AML Relevance:
    - Multi-factor risk scoring is industry best practice
    - Historical scores enable trend analysis
    - Component scores provide explainability
    """
    __tablename__ = "risk_scores"
    
    id = Column(String(36), primary_key=True, index=True)
    account_id = Column(String(36), ForeignKey("accounts.id"), index=True)
    
    # Composite score (0-100)
    composite_score = Column(Float, nullable=False)
    risk_category = Column(String(20))  # low, medium, high
    
    # Component scores (each 0-100)
    transaction_velocity_score = Column(Float, default=0.0)
    beneficiary_diversity_score = Column(Float, default=0.0)
    account_age_score = Column(Float, default=0.0)
    device_reuse_score = Column(Float, default=0.0)
    graph_centrality_score = Column(Float, default=0.0)
    behavior_deviation_score = Column(Float, default=0.0)
    
    # ML model output
    mule_probability = Column(Float, default=0.0)  # 0-100%
    model_confidence = Column(Float, default=0.0)  # 0-100%
    model_version = Column(String(20), default="v1.0")
    
    # Timestamp for historical tracking
    calculated_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    account = relationship("Account", back_populates="risk_scores")


class BehavioralProfile(Base):
    """
    Baseline behavioral profile for anomaly detection.
    
    AML Relevance:
    - Establishes normal transaction patterns
    - Deviations from baseline indicate potential mule activity
    - Time-based patterns reveal suspicious behavior
    """
    __tablename__ = "behavioral_profiles"
    
    id = Column(String(36), primary_key=True, index=True)
    account_id = Column(String(36), ForeignKey("accounts.id"), index=True)
    
    # Transaction frequency baseline
    avg_daily_transactions = Column(Float, default=0.0)
    avg_weekly_transactions = Column(Float, default=0.0)
    avg_monthly_transactions = Column(Float, default=0.0)
    
    # Transaction amount baseline
    avg_transaction_amount = Column(Float, default=0.0)
    min_transaction_amount = Column(Float, default=0.0)
    max_transaction_amount = Column(Float, default=0.0)
    typical_amount_range = Column(JSON)  # [lower, upper] bounds
    
    # Time-of-day patterns
    typical_hours = Column(JSON)  # List of typical active hours
    weekend_activity_ratio = Column(Float, default=0.0)
    
    # Geographic patterns
    typical_locations = Column(JSON)  # List of common IP countries/cities
    geo_diversity_score = Column(Float, default=0.0)
    
    # Beneficiary patterns
    unique_beneficiaries = Column(Integer, default=0)
    recurring_beneficiaries = Column(JSON)  # Frequently transacted accounts
    
    # Profile metadata
    profile_version = Column(String(20), default="v1.0")
    samples_count = Column(Integer, default=0)  # Transactions used to build profile
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Deviation tracking
    current_deviation_score = Column(Float, default=0.0)
    
    # Relationships
    account = relationship("Account", back_populates="behavioral_profiles")


class SARReport(Base):
    """
    Suspicious Activity Report (SAR) for regulatory compliance.
    
    AML Relevance:
    - SAR filing is mandatory for confirmed suspicious activity
    - Reports must include comprehensive transaction details
    - Format follows FinCEN/regulatory requirements
    """
    __tablename__ = "sar_reports"
    
    id = Column(String(36), primary_key=True, index=True)
    report_number = Column(String(30), unique=True, index=True)
    case_id = Column(String(36), index=True)  # Linked investigation case
    
    # Account information
    account_id = Column(String(36), index=True)
    account_details = Column(JSON)  # Full account information snapshot
    
    # Suspicious activity summary
    activity_summary = Column(Text)
    suspicious_patterns = Column(JSON)  # List of detected patterns
    
    # Risk assessment
    risk_score = Column(Float)
    risk_category = Column(String(20))
    mule_probability = Column(Float)
    
    # Explainable AI reasoning
    ai_reasoning = Column(JSON)  # List of AI-generated explanations
    
    # Transaction summary
    transaction_count = Column(Integer)
    total_amount = Column(Float)
    transaction_period_start = Column(DateTime)
    transaction_period_end = Column(DateTime)
    related_transactions = Column(JSON)  # List of transaction IDs
    
    # Network analysis
    connected_accounts = Column(JSON)  # Related accounts in network
    network_risk_summary = Column(Text)
    
    # Report metadata
    generated_at = Column(DateTime, default=datetime.utcnow)
    generated_by = Column(String(100), default="MuleShield AI")
    
    # Filing status
    status = Column(String(20), default="draft")  # draft, submitted, acknowledged
    filed_at = Column(DateTime, nullable=True)
    regulatory_reference = Column(String(50), nullable=True)
